### ISSUE TITLE
Error when initializing training

### ISSUE THREAD

**Issue by michjens** [naiveHobo/InvoiceNet#14]
Whenever i train the model, I can prepare the data, and its located in the correct place, but every time i start the training i get an exception:

> ``Exception in thread Thread-35:
> Traceback (most recent call last):
>   File "C:\Users\Michael\Anaconda3\envs\invoicetest\lib\site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
>     return fn(*args)
>   File "C:\Users\Michael\Anaconda3\envs\invoicetest\lib\site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
>     options, feed_dict, fetch_list, target_list, run_metadata)
>   File "C:\Users\Michael\Anaconda3\envs\invoicetest\lib\site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
>     run_metadata)
> tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
>          [[{{node IteratorGetNext_1}}]]``

I've tried everything i could think of, but I'm unable to get it to work. 

Any tips would be much appreciated

Thanks in advance

**Comment by naiveHobo** [comment]
It looks like it's not able to find any prepared data for training. What is the size of your training dataset? Did you prepare the data before training?

**Comment by michjens** [comment]
Thanks for the quick reply

I just wanted to test it real quick, so i only made a couple of test files for training: 

![image](https://user-images.githubusercontent.com/33859372/90012825-6a09dd00-dca4-11ea-9983-34dbf8e65346.png)

Each JSON only contains 4 different values as well


And yes, i did prepare the data before testing: 
![image](https://user-images.githubusercontent.com/33859372/90012943-9c1b3f00-dca4-11ea-9c61-1e749a54be2e.png)

**Comment by naiveHobo** [comment]
Ah right, tensorflow dataloader throws that error since it is expected there would be some validation data. This is definitely an error that the user should at least be warned about, so thank you for pointing it out. For now, you need at least one sample for validation to satisfy the dataloader so having a dataset of 5 samples should work.

**Comment by michjens** [comment]
That did the job, thanks a lot.

One last question tho, is it normal for it to take this long with such a small batch? I've had it running for ~1 hour now and it's finished: 
![image](https://user-images.githubusercontent.com/33859372/90129261-9c7d0e00-dd68-11ea-968f-a2a3e8bc15e9.png)

And i definitely don't have a bad pc.

Just curious if this is to be expected so i don't end up waiting a day for it to complete only for it to not be intended.

**Comment by naiveHobo** [comment]
With a batch size of 4 I usually get about 0.9-1.0 batches/s on an Nvidia GTX 1050ti for an amount based field. For a general field, I get about 1.0-1.1 batches/s. It drops to about 0.65 and 0.45 respectively with a batch size of 8.

Do you have a GPU? Is CUDA 10.1 installed? I've written the `setup.py` script such that it automatically detects if CUDA is available and will install tensorflow-gpu if it is. Otherwise, it defaults to the tensorflow cpu bindings. Can you check the tensorflow logs to see if you're actually using the GPU if you have one?

**Comment by michjens** [comment]
That's my issue - i don't have a dedicated GPU on my work laptop. I just didn't expect it would be this rough on it given the limited amount of training data i threw at it, but if it's normal then i just need to be a bit patient

**Comment by siddas27** [comment]
I am getting the same error, although I have more than 70 processed data in train and 20 in val. @naiveHobo

**Comment by umairDms** [comment]
can you 

> tensorflow

please if can you explain that how can i solve that, still facing same on macos

**Comment by cobramostar** [comment]
training is not enough,
sorry, but I still didn't understand what data to insert for some validation data
